apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-dp
  labels:
    app: app1
  namespace: ns-app1
spec:
  selector:
    matchLabels:
      app: app1
  replicas: 3
  template:
    metadata:
      labels:
        app: app1
    spec:
      imagePullSecrets:
      - name: ocirsecret
      containers:
      - name: app1
        image: iad.ocir.io/idlhjo6dp3bd/app1:latest
        ports:
        - containerPort: 80
