apiVersion: v1
kind: Service
metadata:
  name: app-argocd-svc
  namespace: app-argocd
spec:
  selector:
    app: app-argocd
  ports:
    - port: 8088
      targetPort: 80
      protocol: TCP
  type: ClusterIP

